CREATE DATABASE FBD2022
	ON PRIMARY(NAME='FBD2022',
		FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FBD2022.MDF',
		SIZE=200MB,MAXSIZE=500MB,FILEGROWTH=25%)
	LOG ON
		(NAME='FBD2022_LOG', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FBD2022_LOG.LDF', 
		SIZE=100MB, MAXSIZE=250MB,FILEGROWTH=25%)

USE FBD2022;
---creaci�n es esquema
CREATE SCHEMA RRHH;
CREATE SCHEMA FACULTAD;

--Crear tablas y constraints
CREATE TABLE RRHH.PERSONA 
	(
		CIF INT PRIMARY KEY, 
		NOMBRE VARCHAR(100) NOT NULL,
		TELEFONO INT,
		DIRECCION VARCHAR(150),
		FECHA_INGRESO DATETIME NOT NULL,
		EDAD INT  --CHECK(EDAD > 17)
		--CONSTRAINT DF_DIRECCION DEFAULT 'MANAGUA' FOR DIRECCION,
		--CONSTRAINT DF_FECHAINGRESO DEFAULT (GETDATE()) FOR FECHA_INGRESO,
		--CONSTRAINT CK_EDAD CHECK(EDAD > 17)
)

ALTER TABLE [RRHH].[PERSONA]
	--DROP CONSTRAINT [PK__PERSONA__C1F8DC5FD35312EB]
	--ADD CONSTRAINT PK_CIF PRIMARY KEY(CIF)
	--ADD CONSTRAINT DF_DIRECCION DEFAULT 'MANAGUA' FOR DIRECCION
	--ADD CONSTRAINT DF_FECHAINGRESO DEFAULT (GETDATE()) FOR FECHA_INGRESO
	--ADD CONSTRAINT CK_EDAD CHECK (EDAD > 17)
	ADD CONSTRAINT UQ_TELEFONO UNIQUE (TELEFONO)

CREATE TABLE RRHH.ESTUDIANTE
	(
		CIF INT, 
		PADRE VARCHAR(100) CONSTRAINT DF_PADRE DEFAULT 'N/A',
		MADRE VARCHAR(100) DEFAULT 'N/A',
		SEGURO INT,
		CONSTRAINT PK_CIF_ESTUDIANTE PRIMARY KEY (CIF),
		CONSTRAINT FK_CIF_PERSONA_ESTUDIANTE FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)
)

ALTER TABLE [RRHH].[ESTUDIANTE]
	ADD CONSTRAINT FK_CIF_PERSONA_ESTUDIANTE FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)


USE FBD2022;

CREATE TABLE ASIGNATURA
(
	ID_ASIG INT PRIMARY KEY,
	NOMBRE VARCHAR(100), 
	DESCRIPCION VARCHAR(100)

)

EXEC SP_RENAME '[dbo].[ASIGNATURA]', 'ASIGNATURAR';
EXEC SP_RENAME '[dbo].[ASIGNATURAR]', 'ASIGNATURA';
EXEC SP_RENAME '[dbo].[ASIGNATURA].[ID_ASIG]', 'ID_ASIGNATURA', 'COLUMN';
EXEC SP_RENAME '[PK__ASIGNATU__624B5CD8249E27D9]', 'PK__IDASIGNATURA__624B5CD8249E27D9';

CREATE TABLE FACULTAD.MATRICULA
(
	CIF INT NOT NULL,
	ID_ASIG INT NOT NULL,
	SEMESTRE INT,
	ANIO INT, 
	CONSTRAINT FK_CIF_ESTUDIANTE_MATRICULA FOREIGN KEY (CIF) REFERENCES [RRHH].[ESTUDIANTE](CIF)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT FK_IDASIG_ASIGNATURA_MATRICULA FOREIGN KEY (ID_ASIG) REFERENCES [dbo].[ASIGNATURA]([ID_ASIGNATURA])
		ON UPDATE CASCADE 
		ON DELETE CASCADE
)

ALTER TABLE [RRHH].[ESTUDIANTE]
	--DROP CONSTRAINT [FK_CIF_PERSONA_ESTUDIANTE]
	ADD CONSTRAINT [FK_CIF_PERSONA_ESTUDIANTE] FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)
		ON UPDATE CASCADE
		ON DELETE CASCADE


CREATE TABLE RRHH.TIPO_DOCENTE(
	ID_TIPO INT PRIMARY KEY,
	NOMBRE VARCHAR(100)
)

CREATE TABLE RRHH.DOCENTE
(
	CIF INT PRIMARY KEY,
	SALARY MONEY,
	ID_TIPO INT,
	CONSTRAINT FK_CIF_PERSONA_DOCENTE FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT FK_IDTIPO_TIPODOCENTE_DOCENTE FOREIGN KEY (ID_TIPO) REFERENCES RRHH.TIPO_DOCENTE(ID_TIPO)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

ALTER SCHEMA FACULTAD TRANSFER [dbo].[ASIGNATURA]

CREATE TABLE [RRHH].CARGO
(
	ID_CARGO INT PRIMARY KEY,
	NOMBRE VARCHAR(100)
)

CREATE TABLE ADMINISTRATIVO
(
	CIF INT PRIMARY KEY,
	CONSTRAINT FK_CIFADMINISTRATIVO FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA] (CIF)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	SESION VARCHAR(100),
	GENERO VARCHAR(1),
	ESTADO_CIVIL VARCHAR(10),
	ID_CARGO INT,
	CONSTRAINT FK_IDCARGOADMINISTRATIVO FOREIGN KEY (ID_CARGO) REFERENCES [RRHH].[CARGO] (ID_CARGO)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

ALTER SCHEMA [RRHH] 
	TRANSFER [dbo].[ADMINISTRATIVO]


INSERT INTO [RRHH].[PERSONA]
	VALUES(1, 'LESTER RODRIGUEZ', 84845652, DEFAULT, DEFAULT, 18),
	(2, 'SILVIO VIGIL', 84845653, DEFAULT, DEFAULT, 20),
	(3, 'EDDY SILVA', 84845654, DEFAULT, DEFAULT, 19),
	(4, 'EMILIANO QUINTERO', 84845655, DEFAULT, DEFAULT, 20),
	(5, 'MARCOS SANCHEZ', 84845656, DEFAULT, DEFAULT, 21)

SELECT * FROM [RRHH].[PERSONA]

INSERT INTO [RRHH].[ESTUDIANTE]
	VALUES(2, 'PADRE', 'MADRE', 1305),
	(5, 'PADRE', 'MADRE', 1305),
	(1, 'PADRE', 'MADRE', 1305)

SELECT * FROM [RRHH].[ESTUDIANTE]

SELECT  A.CIF AS ID, B.NOMBRE, A.PADRE, A.MADRE, A.SEGURO
FROM [RRHH].[ESTUDIANTE] A, [RRHH].[PERSONA] B
WHERE A.CIF = B.CIF

UPDATE [RRHH].[PERSONA]
	SET CIF = 6
	WHERE CIF = 2

DELETE FROM [RRHH].[PERSONA]
	WHERE CIF = 6

INSERT INTO [RRHH].[PERSONA]
	--VALUES (2, 'SILVIO VIGIL', 84845653, DEFAULT, DEFAULT, 20)
	VALUES (6, 'MEGAN BOUGLE', 84845657, 'MASAYA', DEFAULT, 21),
	(7, 'ELIAS ZELEDON', 84845658, 'CARAZO', DEFAULT, 21)

SELECT NOMBRE, EDAD=
	CASE EDAD
		WHEN 18 THEN 'MENOR'
		WHEN 20 THEN 'MAYOR'
		ELSE 'OTRA'
	END 
FROM [RRHH].[PERSONA]

SELECT NOMBRE, DIRECCION=
	CASE DIRECCION
		WHEN 'MANAGUA' THEN 'DE AQUÍ'
		ELSE 'FORÁNEO'
	END 
FROM [RRHH].[PERSONA]

SELECT CIF, NOMBRE, DIRECCION 
FROM [RRHH].[PERSONA]
WHERE DIRECCION NOT IN ('MASAYA', 'CARAZO')

SELECT CIF, NOMBRE, EDAD 
FROM [RRHH].[PERSONA]
WHERE EDAD BETWEEN 18 AND 20

SELECT CIF, NOMBRE, DIRECCION 
FROM [RRHH].[PERSONA]
WHERE DIRECCION LIKE 'MA%'

SELECT DISTINCT DIRECCION 
FROM [RRHH].[PERSONA]
--WHERE DIRECCION LIKE 'MA%'

SELECT TOP 3 *
FROM [RRHH].[PERSONA]
ORDER BY CIF DESC

SELECT P.CIF AS CIF_PER, NOMBRE, E.SEGURO AS SEGURO_EST, *
FROM [RRHH].[PERSONA] P, [RRHH].[ESTUDIANTE] E
WHERE P.CIF = E.CIF

SELECT P.CIF, NOMBRE
FROM [RRHH].[PERSONA] AS P
INNER JOIN [RRHH].[ESTUDIANTE] AS E
ON P.CIF = E.CIF

SELECT P.CIF, NOMBRE, E.SEGURO
FROM [RRHH].[PERSONA] AS P RIGHT JOIN [RRHH].[ESTUDIANTE] AS E
ON P.CIF = E.CIF

SELECT P.CIF, NOMBRE, E.SEGURO
FROM [RRHH].[PERSONA] AS P LEFT JOIN [RRHH].[ESTUDIANTE] AS E
ON P.CIF = E.CIF
WHERE SEGURO IS NULL

SELECT P.CIF, NOMBRE, E.SEGURO
FROM [RRHH].[PERSONA] AS P FULL JOIN [RRHH].[ESTUDIANTE] AS E
ON P.CIF = E.CIF


CREATE VIEW VW_CONOCIDOS
AS
SELECT P.CIF, NOMBRE, E.SEGURO
FROM [RRHH].[PERSONA] AS P FULL JOIN [RRHH].[ESTUDIANTE] AS E
ON P.CIF = E.CIF

SELECT  * FROM [dbo].[VW_CONOCIDOS]