CREATE DATABASE FBD2022
	ON PRIMARY(NAME='FBD2022',
		FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FBD2022.MDF',
		SIZE=200MB,MAXSIZE=500MB,FILEGROWTH=25%)
	LOG ON
		(NAME='FBD2022_LOG', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FBD2022_LOG.LDF', 
		SIZE=100MB, MAXSIZE=250MB,FILEGROWTH=25%)

USE FBD2022;
---creaci�n es esquema
CREATE SCHEMA RRHH;
CREATE SCHEMA FACULTAD;

--Crear tablas y constraints
CREATE TABLE RRHH.PERSONA 
	(
		CIF INT PRIMARY KEY, 
		NOMBRE VARCHAR(100) NOT NULL,
		TELEFONO INT,
		DIRECCION VARCHAR(150),
		FECHA_INGRESO DATETIME NOT NULL,
		EDAD INT  --CHECK(EDAD > 17)
		--CONSTRAINT DF_DIRECCION DEFAULT 'MANAGUA' FOR DIRECCION,
		--CONSTRAINT DF_FECHAINGRESO DEFAULT (GETDATE()) FOR FECHA_INGRESO,
		--CONSTRAINT CK_EDAD CHECK(EDAD > 17)
)

ALTER TABLE [RRHH].[PERSONA]
	--DROP CONSTRAINT [PK__PERSONA__C1F8DC5FC513DBFA]
	--ADD CONSTRAINT PK_CIF PRIMARY KEY(CIF)
	--ADD CONSTRAINT DF_DIRECCION DEFAULT 'MANAGUA' FOR DIRECCION
	--ADD CONSTRAINT DF_FECHAINGRESO DEFAULT (GETDATE()) FOR FECHA_INGRESO
	--ADD CONSTRAINT CK_EDAD CHECK (EDAD > 17)

CREATE TABLE RRHH.ESTUDIANTE
	(
		--CIF INT, 
		--PADRE VARCHAR(100) CONSTRAINT DF_PADRE DEFAULT 'N/A',
		--MADRE VARCHAR(100) DEFAULT 'N/A',
		--SEGURO INT,
		--CONSTRAINT PK_CIF_ESTUDIANTE PRIMARY KEY (CIF),
		--CONSTRAINT FK_CIF_PERSONA_ESTUDIANTE FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)
)

ALTER TABLE [RRHH].[ESTUDIANTE]
	ADD CONSTRAINT FK_CIF_PERSONA_ESTUDIANTE FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)


USE FBD2022;

CREATE TABLE ASIGNATURA
(
	ID_ASIG INT PRIMARY KEY,
	NOMBRE VARCHAR(100), 
	DESCRIPCION VARCHAR(100)

)

--EXEC SP_RENAME '[dbo].[ASIGNATURA]', 'ASIGNATURAR';
--EXEC SP_RENAME '[dbo].[ASIGNATURAR]', 'ASIGNATURA';
--EXEC SP_RENAME '[dbo].[ASIGNATURA].[ID_ASIG]', 'ID_ASIGNATURA', 'COLUMN';
--EXEC SP_RENAME '[PK__ASIGNATU__624B5CD8249E27D9]', 'PK__IDASIGNATURA__624B5CD8249E27D9';

CREATE TABLE FACULTAD.MATRICULA
(
	CIF INT NOT NULL,
	ID_ASIG INT NOT NULL,
	SEMESTRE INT,
	ANIO INT, 
	CONSTRAINT FK_CIF_ESTUDIANTE_MATRICULA FOREIGN KEY (CIF) REFERENCES [RRHH].[ESTUDIANTE](CIF)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT FK_IDASIG_ASIGNATURA_MATRICULA FOREIGN KEY (ID_ASIG) REFERENCES [dbo].[ASIGNATURA]([ID_ASIGNATURA])
		ON UPDATE CASCADE 
		ON DELETE CASCADE
)

ALTER TABLE [RRHH].[ESTUDIANTE]
	--DROP CONSTRAINT [FK_CIF_PERSONA_ESTUDIANTE]
	ADD CONSTRAINT [FK_CIF_PERSONA_ESTUDIANTE] FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)
		ON UPDATE CASCADE
		ON DELETE CASCADE


CREATE TABLE RRHH.TIPO_DOCENTE(
	ID_TIPO INT PRIMARY KEY,
	NOMBRE VARCHAR(100)
)

CREATE TABLE RRHH.DOCENTE
(
	CIF INT PRIMARY KEY,
	SALARY MONEY,
	ID_TIPO INT,
	CONSTRAINT FK_CIF_PERSONA_DOCENTE FOREIGN KEY (CIF) REFERENCES [RRHH].[PERSONA](CIF)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT FK_IDTIPO_TIPODOCENTE_DOCENTE FOREIGN KEY (ID_TIPO) REFERENCES RRHH.TIPO_DOCENTE(ID_TIPO)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

ALTER SCHEMA FACULTAD TRANSFER [dbo].[ASIGNATURA]