-- SQL SCRIPT PARA AP11:

--IGNORAR ESTAS DOS LÍNEAS
SELECT ID_PERSONALACTIVO AS ID, COD_CARGO AS COD
FROM [RRHH].[PersonalActivoXCargo]


CREATE DATABASE REGISTROPRESTAMOSBIBLIOTECAUAMPAC
	ON PRIMARY(NAME='REGISTROPRESTAMOSBIBLIOTECAUAMPAC',
		FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\REGISTROPRESTAMOSBIBLIOTECAUAMPAC.MDF',
		SIZE=200MB,MAXSIZE=500MB,FILEGROWTH=25%)
	LOG ON
		(NAME='REGISTROPRESTAMOSBIBLIOTECAUAMPAC_LOG', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\REGISTROPRESTAMOSBIBLIOTECAUAMPAC_LOG.LDF', 
		SIZE=100MB, MAXSIZE=250MB,FILEGROWTH=25%)

USE REGISTROPRESTAMOSBIBLIOTECAUAMPAC;

--CREACION DE BASE DE DATOS y USE
/* Commands completed successfully.

Completion time: 2022-11-08T07:52:17.0571600-06:00 */

CREATE SCHEMA CATALOGO;

--CREACION DE ESQUEMA CATALOGO
/* Commands completed successfully.

Completion time: 2022-11-08T07:55:49.0371272-06:00 */

CREATE SCHEMA RRHH;

--CREACION DE ESQUEMA RRHH
/* Commands completed successfully.

Completion time: 2022-11-08T07:56:07.0292345-06:00 */

CREATE SCHEMA PRESTAMOS;

--CREACION DE ESQUEMA PRESTAMOS
/* Commands completed successfully.

Completion time: 2022-11-08T07:56:21.8953344-06:00 */

CREATE TABLE [CATALOGO].Autor
(
	COD_AUTOR varchar(10) PRIMARY KEY,
	NOMBRE_AUTOR varchar(50) NOT NULL
)

CREATE TABLE [CATALOGO].Editorial
(
	COD_EDITORIAL varchar(12) PRIMARY KEY,
	NOMBRE_EDITORIAL VARCHAR(20) NOT NULL
)

CREATE TABLE [CATALOGO].Clasificacion
(
	COD_CLASIFICACION VARCHAR(12) PRIMARY KEY,
	NOMBRE_CLASIFICACION VARCHAR(25) NOT NULL
)

--CREACION DE tablas autor, editorial, y clasificacion (esquema catálogo)
/* 
Commands completed successfully.

Completion time: 2022-11-08T08:21:38.3116920-06:00
*/

CREATE TABLE [CATALOGO].Libro
(
	ISBN varchar(14) PRIMARY KEY,
	TITULO_LIBRO VARCHAR(30) NOT NULL,
	MFN VARCHAR(12) NOT NULL,
	EDITORIAL VARCHAR(12) NOT NULL,
	CLASIFICACION VARCHAR(12) NOT NULL,

	CONSTRAINT FK_CODEDITORIAL_EDITORIAL_LIBRO FOREIGN KEY (EDITORIAL) REFERENCES [CATALOGO].Editorial (COD_EDITORIAL),
	CONSTRAINT FK_CODCLASIFICACION_CLASIFICACION_LIBRO FOREIGN KEY (CLASIFICACION) REFERENCES [CATALOGO].Clasificacion (COD_CLASIFICACION)
)

--Creación de tabla libro (FKs: editorial y clasificacion)
/* Commands completed successfully.

Completion time: 2022-11-08T10:24:29.9585701-06:00 */


ALTER TABLE [CATALOGO].Libro
	--DROP CONSTRAINT FK_CODEDITORIAL_EDITORIAL_LIBRO
	--DROP CONSTRAINT FK_CODCLASIFICACION_CLASIFICACION_LIBRO

	/* ADD CONSTRAINT FK_CODEDITORIAL_EDITORIAL_LIBRO FOREIGN KEY (EDITORIAL) REFERENCES [CATALOGO].Editorial (COD_EDITORIAL)
		ON UPDATE CASCADE
		ON DELETE CASCADE */

	/* ADD CONSTRAINT FK_CODCLASIFICACION_CLASIFICACION_LIBRO FOREIGN KEY (CLASIFICACION) REFERENCES [CATALOGO].Clasificacion (COD_CLASIFICACION)
		ON UPDATE CASCADE
		ON DELETE CASCADE */

	ADD CONSTRAINT UQ_MFN UNIQUE (MFN)
	
--Alteración a [CATALOGO].Libro (se me olvidó los on update/delete cascade xD), TAMBIÉN AGRUEGUÉ UNIQUE CONSTRAINT A MFN
/* Commands completed successfully.

Completion time: 2022-11-08T10:37:41.6218386-06:00 */

CREATE TABLE AutorXLibro
(
	AUTOR VARCHAR(10) NOT NULL,
	ISBN VARCHAR(14) NOT NULL,

	CONSTRAINT FK_CODAUTOR_AUTOR_AUTORXLIBRO FOREIGN KEY (AUTOR) REFERENCES [CATALOGO].[Autor](COD_AUTOR)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	CONSTRAINT FK_ISBN_LIBRO_AUTORXLIBRO FOREIGN KEY (ISBN) REFERENCES [CATALOGO].[Libro](ISBN)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	CONSTRAINT PK_AUTORXLIBRO PRIMARY KEY(AUTOR, ISBN)
)

--CREACION DE TABLA AUTORXLIBRO (FKs: Autor y ISBN) (PK compuesta: ambas FKs)
/* Commands completed successfully.

Completion time: 2022-11-08T10:49:36.5862515-06:00 */

ALTER SCHEMA [CATALOGO]
	TRANSFER [dbo].[AutorXLibro]

--ALTERACIÓN AL ESQUEMA CATÁLOGO (SE ME OLVIDÓ CREAR LA TABLA AUTORXLIBRO EN ESE ESQUEMA, UPS)
/* Commands completed successfully.

Completion time: 2022-11-08T10:52:19.1469211-06:00 */

CREATE TABLE [CATALOGO].Ubicacion
(
	COD_UBICACION VARCHAR(14) PRIMARY KEY,
	NOMBRE VARCHAR(10) NOT NULL
)

--CREACIÓN DE TABLA UBICACION (ESQUEMA CATALOGO)
/* Commands completed successfully.

Completion time: 2022-11-08T10:58:39.9651555-06:00 */

CREATE TABLE [CATALOGO].EJEMPLAR
(
	COD_INVENTARIO VARCHAR(10) PRIMARY KEY,
	ESTADO BIT NOT NULL,
	NUMERO_COPIA INT NOT NULL,
	ISBN VARCHAR(14) NOT NULL,
	UBICACION VARCHAR(14) NOT NULL,

	CONSTRAINT FK_ISBN_LIBRO_EJEMPLAR FOREIGN KEY (ISBN) REFERENCES [CATALOGO].[Libro](ISBN)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	CONSTRAINT FK_CODUBICACION_UBICACION_EJEMPLAR FOREIGN KEY (UBICACION) REFERENCES [CATALOGO].[Ubicacion](COD_UBICACION)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

--CREACION DE TABLA EJEMPLAR (ESQUEMA CATALOGO) (FKs: ISBN y COD_UBICACION)
/* Commands completed successfully.

Completion time: 2022-11-08T11:08:00.3805911-06:00 */

ALTER TABLE [CATALOGO].EJEMPLAR
	ADD CONSTRAINT DF_ESTADO DEFAULT NULL FOR ESTADO

--AGREGUÉ DEFAULT CONSTRAINT PARA ESTADO (NULL) SI NO SE PONE 0 (NO DISPONIBLE) o 1 (DISPONIBLE)
/* Commands completed successfully.

Completion time: 2022-11-08T13:58:44.6340188-06:00 */

EXEC SP_RENAME '[CATALOGO].[EJEMPLAR]', 'Ejemplar'

-- RENAME A LA TABLA EJEMPLAR, PARA QUE NO ESTÉ TODO EN MAYÚSCULAS
/* Precaución: Al cambiar cualquier parte del nombre de un objeto, los scripts y procedimientos almacenados pueden dejar de funcionar.

Completion time: 2022-11-08T11:13:34.6027243-06:00 */

CREATE TABLE [RRHH].Cargo
(
	COD_CARGO VARCHAR(3) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE [RRHH].Facultad
(
	COD_FACULTAD VARCHAR(3) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
)

CREATE TABLE [RRHH].Carrera
(
	COD_CARRERA VARCHAR(3) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
)

--CREACION DE TABLAS CARGO, FACULTAD, Y CARRERA (ESQUEMA RRHH)
/* Commands completed successfully.

Completion time: 2022-11-08T11:21:57.6215467-06:00 */

CREATE TABLE [RRHH].Persona
(
	ID_PERSONA VARCHAR(16) PRIMARY KEY,
	NOMBRES VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(14) NOT NULL,
)

--CREACION DE TABLA PERSONA (ESQUEMA RRHH)
/* Commands completed successfully.

Completion time: 2022-11-08T11:25:27.6788017-06:00 */

CREATE TABLE [RRHH].Docente
(
	ID_DOCENTE VARCHAR(14) PRIMARY KEY,
	ID_PERSONA VARCHAR(16) NOT NULL,

	CONSTRAINT FK_IDPERSONA_PERSONA_DOCENTE FOREIGN KEY (ID_PERSONA) REFERENCES [RRHH].[Persona] (ID_PERSONA)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

CREATE TABLE [RRHH].Estudiante
(
	ID_ESTUDIANTE VARCHAR(14) PRIMARY KEY,
	ID_PERSONA VARCHAR(16) NOT NULL,

	CONSTRAINT FK_IDPERSONA_PERSONA_ESTUDIANTE FOREIGN KEY (ID_PERSONA) REFERENCES [RRHH].[Persona] (ID_PERSONA)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

CREATE TABLE [RRHH].PersonalActivo
(
	ID_PERSONALACTIVO VARCHAR(14) PRIMARY KEY,
	ID_PERSONA VARCHAR(16) NOT NULL,

	CONSTRAINT FK_IDPERSONA_PERSONA_PERSONALACTIVO FOREIGN KEY (ID_PERSONA) REFERENCES [RRHH].[Persona] (ID_PERSONA)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

--CREACION DE TABLAS ESTUDIANTE, DOCENTE, Y PERSONAL ACTIVO (ESQUEMA RRHH)
/* Commands completed successfully.

Completion time: 2022-11-08T11:37:18.3264087-06:00 */


CREATE TABLE [RRHH].DocenteXFacultad
(
	ID_DOCENTE VARCHAR(14) NOT NULL,
	COD_FACULTAD VARCHAR(3) NOT NULL,

	CONSTRAINT FK_IDDOCENTE_DOCENTE_DOCENTEXFACULTAD FOREIGN KEY (ID_DOCENTE) REFERENCES [RRHH].[Docente](ID_DOCENTE)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT FK_CODFACULTAD_FACULTAD_DOCENTEXFACULTAD FOREIGN KEY (COD_FACULTAD) REFERENCES [RRHH].[Facultad](COD_FACULTAD)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT PK_DOCENTEXFACULTAD PRIMARY KEY(ID_DOCENTE, COD_FACULTAD)
)

--CREACION DE TABLA INTERMEDIA DOCENTE X FACULTAD (ESQUEMA RRHH) (FKs. id_docente y cod_facultad) (PK compuesta: ambas FKs)
/* Commands completed successfully.

Completion time: 2022-11-08T11:45:25.5100380-06:00 */

CREATE TABLE [RRHH].EstudianteXCarrera
(
	ID_ESTUDIANTE VARCHAR(14) NOT NULL,
	COD_CARRERA VARCHAR(3) NOT NULL,

	CONSTRAINT FK_IDESTUDIANTE_ESTUDIANTE_ESTUDIANTEXCARRERA FOREIGN KEY (ID_ESTUDIANTE) REFERENCES [RRHH].[Estudiante](ID_ESTUDIANTE)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT FK_CODCARRERA_CARRERA_ESTUDIANTEXCARRERA FOREIGN KEY (COD_CARRERA) REFERENCES [RRHH].[Carrera](COD_CARRERA)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT PK_ESTUDIANTEXCARRERA PRIMARY KEY(ID_ESTUDIANTE, COD_CARRERA)
)

CREATE TABLE [RRHH].PersonalActivoXCargo
(
	ID_PERSONALACTIVO VARCHAR(14) NOT NULL,
	COD_CARGO VARCHAR(3) NOT NULL,

	CONSTRAINT FK_IDPERSONALACTIVO_PERSONALACTIVO_PERSONALACTIVOXCARGO FOREIGN KEY (ID_PERSONALACTIVO) REFERENCES [RRHH].[PersonAlactivo](ID_PERSONALACTIVO)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT FK_CODCARGO_CARGO_PERSONALACTIVOXCARGO FOREIGN KEY (COD_CARGO) REFERENCES [RRHH].[Cargo](COD_CARGO)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT PK_PERSONALACTIVOXCARGO PRIMARY KEY(ID_PERSONALACTIVO, COD_CARGO)
)

--CREACIÓN DE TABLAS INTERMEDIAS ESTUDIANTEXCARRERA Y PERSONALACTIVOXCARGO
/* Commands completed successfully.

Completion time: 2022-11-08T11:59:50.5231522-06:00 */

CREATE TABLE [PRESTAMOS].Prestamo
(
	COD_PRESTAMO VARCHAR(12) PRIMARY KEY,
	F_EMISION DATETIME NOT NULL,
	F_DEVOLUCION DATETIME NOT NULL,
	MORA int NOT NULL,
	ESTADO BIT NOT NULL,

	ID_PERSONA VARCHAR(16) NOT NULL,

	CONSTRAINT FK_IDPERSONA_PERSONA_PRESTAMO FOREIGN KEY (ID_PERSONA) REFERENCES [RRHH].[Persona](ID_PERSONA)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)

--CREACION DE TABLA PRESTAMO (ESQUEMA PRESTAMO)
/*Commands completed successfully.

Completion time: 2022-11-08T12:14:14.0461386-06:00 */

ALTER TABLE [PRESTAMOS].Prestamo
	ADD CONSTRAINT CHK_FECHADEV CHECK (F_DEVOLUCION > GETDATE())

--ALTERACION PARA ADD CHECK CONSTRAINT A FECHA DE DEVOLUCION (QUE NO SEA MENOR A LA FECHA DE HOY)
/* Commands completed successfully.

Completion time: 2022-11-08T14:27:56.6504429-06:00 */

ALTER TABLE [PRESTAMOS].Prestamo
	--ADD CONSTRAINT DF_MORA DEFAULT 0 FOR MORA
	ADD CONSTRAINT DF_ESTADO DEFAULT 1 FOR ESTADO

--Alteraciones add constraint df_mora y df_estado
/* Commands completed successfully.

Completion time: 2022-11-08T14:09:19.6880298-06:00

Commands completed successfully.

Completion time: 2022-11-08T14:10:58.9751508-06:00 */

CREATE TABLE [PRESTAMOS].PrestamoXEjemplar
(
	COD_INVENTARIO VARCHAR(10) NOT NULL,
	COD_PRESTAMO VARCHAR(12) NOT NULL,

	CONSTRAINT FK_CODINVENTARIO_EJEMPLAR_PRESTAMOXEJEMPLAR FOREIGN KEY (COD_INVENTARIO) REFERENCES [CATALOGO].[Ejemplar](COD_INVENTARIO)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT FK_CODPRESTAMO_PRESTAMO_PRESTAMOXEJEMPLAR FOREIGN KEY (COD_PRESTAMO) REFERENCES [PRESTAMOS].[Prestamo](COD_PRESTAMO)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	
	CONSTRAINT PK_PRESTAMOXEJEMPLAR PRIMARY KEY(COD_INVENTARIO, COD_PRESTAMO)
)

--CREACION DE TABLA INTERMEDIA PRESTAMOXEJEMPLAR (FKs: COD_INVENTARIO Y COD_PRESTAMO) (PK: COMPUESTA DE AMBAS FKs)
/*Commands completed successfully.

Completion time: 2022-11-08T12:18:21.3418700-06:00
*/
