-- SQL SCRIPT PARA AP11:

CREATE DATABASE REGISTROPRESTAMOSBIBLIOTECAUAMPAC
	ON PRIMARY(NAME='REGISTROPRESTAMOSBIBLIOTECAUAMPAC',
		FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\REGISTROPRESTAMOSBIBLIOTECAUAMPAC.MDF',
		SIZE=200MB,MAXSIZE=500MB,FILEGROWTH=25%)
	LOG ON
		(NAME='REGISTROPRESTAMOSBIBLIOTECAUAMPAC_LOG', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\REGISTROPRESTAMOSBIBLIOTECAUAMPAC_LOG.LDF', 
		SIZE=100MB, MAXSIZE=250MB,FILEGROWTH=25%)

USE REGISTROPRESTAMOSBIBLIOTECAUAMPAC;

--CREACION DE BASE DE DATOS:
/* Commands completed successfully.

Completion time: 2022-11-08T07:52:17.0571600-06:00 */

CREATE SCHEMA CATALOGO;

--CREACION DE ESQUEMA CATALOGO
/* Commands completed successfully.

Completion time: 2022-11-08T07:55:49.0371272-06:00 */

CREATE SCHEMA RRHH;

--CREACION DE ESQUEMA RRHH
/* Commands completed successfully.

Completion time: 2022-11-08T07:56:07.0292345-06:00 */

CREATE SCHEMA PRESTAMOS;

--CREACION DE ESQUEMA PRESTAMOS
/* Commands completed successfully.

Completion time: 2022-11-08T07:56:21.8953344-06:00 */

CREATE TABLE [CATALOGO].Autor
(
	COD_AUTOR varchar(10) PRIMARY KEY,
	NOMBRE_AUTOR varchar(50) NOT NULL
)

CREATE TABLE [CATALOGO].Editorial
(
	COD_EDITORIAL varchar(12) PRIMARY KEY,
	NOMBRE_EDITORIAL VARCHAR(20) NOT NULL
)

CREATE TABLE [CATALOGO].Clasificacion
(
	COD_CLASIFICACION VARCHAR(12) PRIMARY KEY,
	NOMBRE_CLASIFICACION VARCHAR(25) NOT NULL
)

--CREACION DE tablas autor, editorial, y clasificacion (esquema catálogo)
/* 
Commands completed successfully.

Completion time: 2022-11-08T08:21:38.3116920-06:00
*/

