--WAYS OF RENAMING STUFF (ALIAS)
-- ALIAS = COLUMNNAME
-- COLUMNNAME AS ALIAS
-- COLUMNNAME ALIAS (JUST A SPACE)

--SELECT (ALIAS "NOMBREDB" AS THE NAME COLUMN), recovery_model_desc column AS "MODORECUPERACION"
SELECT NOMBREDB=NAME, recovery_model_desc AS MODORECUPERACION 

--INSERT INTO A TEMB DB, SE METE EN tempdb/temporaryTables
INTO #NOMBREDBLOCAL

--all SYS databases
FROM SYS.DATABASES

--CONDITION OPERATORS (NOT LIKE, LIKE, IN)
-- "NOT LIKE" AND "LIKE" WORK WITH 1 VALUE WHICH YOU DON'T WANT/DO WANT
-- "IN" WORKS WITH ONE OR MULTIPLE VALUES YOU WANT TO INCLUDE, SEPARATED BY PARENTHESIS
WHERE recovery_model_desc NOT LIKE 'SIMPLE'

/* (4 rows affected)

Completion time: 2022-11-07T09:43:02.4170667-06:00 */

--SELECT * MEANS SELECT EVERYTHING
SELECT *

--DRAG IT FROM THE OBJECT EXPLORER
--LOCAL TEMBDBs ONLY WORK WITH CURRENT SESSIONS (QUERY, KINDA)
FROM [dbo].[#NOMBREDBLOCAL______________________________________________________________________________________________________000000000005]