--SWITCH INTO A BRANCH
--DONT USE TEMPDB, I MESSED UP IN CLASS, TEACHER USED A "PRUEBA" DB
USE tempdb;

--THESE TWO LINES DISPLAY EVERYTHING IN THE TABLE
SELECT * 
FROM [dbo].[ESTUDIANTE]

--INSERT VALUES
INSERT INTO [dbo].[ESTUDIANTE]
	VALUES('19014795', 'GABRIEL', '88888888'),
	('666666', 'JUAN', '22222222')

--DELETE WITH CONDITION
DELETE FROM [dbo].[ESTUDIANTE]
WHERE NOMBRE LIKE 'GABRIEL'

--TRUNCATE (DROP AND CREATE)
TRUNCATE TABLE [dbo].[ESTUDIANTE]
